server:
  port: 8082


management:
  endpoint:
    health:
      show-details: ALWAYS
  tracing:
    enabled: true
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
    export:
      prometheus:
        enabled: true

spring:
  application:
    name: gateway
  graphql:
    graphiql:
      path: /graphiql
      enabled: true


springdoc:
  #  enable-spring-security: true
  #  show-login-endpoint: true
  #  show-oauth2-endpoints: true
  show-actuator: true
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha


logging:
  level:
    root: INFO
    com.agilesolutions.kafka: DEBUG
    org.springframework.jpa: DEBUG
    org.springframework.mongo: DEBUG
    org.springframework.security: DEBUG
    org.springframework.graphql: DEBUG

twelvedata:
  api:
    url: https://api.twelvedata.com/
    key: demo