apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: services
resources:
- ../../base
patches:
  - path: ./service-patch.yaml
images:
  - name: account-service
    newName: agilesolutions/account-service
    newTag: 1.0.1
labels:
- includeSelectors: true
  pairs:
    env: local
