apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: services
  labels:
    app: account-service
spec:
  selector:
    app: account-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP  # internal-only, exposed via Ingress