apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap-prometheus.yaml
  - configmap-grafana-dashboards-provider.yaml
  - configmap-grafana-dashboards.yaml
  - configmap-grafana-datasources.yaml
  - deployment-prometheus.yaml
  - deployment-grafana.yaml
  - service-prometheus.yaml
  - service-grafana.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml